### ISSUE TITLE
Using λ~> with Rackjure's applicable dictionaries 

### ISSUE THREAD

**Issue by dkvasnicka** [lexi-lambda/threading#11]
Hi, I'm trying to use `λ~>` with applicable dictionaries and I'm running into an issue where Racket complains `'x` is not a procedure:

```
#lang rackjure

(define h (hasheq 'x (hasheq 'y 1)))

; works
(~> h 'x 'y)

; works
((λ (v) (~> v 'x 'y)) h)

; fails: expected a procedure that can be applied to arguments, given: 'x
((λ~> 'x 'y) h) 
```

Am I doing something wrong? Looks like somehow Rackjure doesn't kick in when running the last example.

**Comment by dkvasnicka** [comment]
A nice workaround is to use the applicable version of `hash-ref-nested-lens` from the `lens` pkg.

**Comment by lexi-lambda** [comment]
This seems related to #3, which was the same issue, but for `~>`. I will investigate.

**Comment by dkvasnicka** [comment]
Works like a charm, thanks!
