### ISSUE TITLE
Use the lexical context of the `~>`

### ISSUE THREAD

**Issue by greghendershott** [lexi-lambda/threading#3]
[Split out as requested from #1]

Doing so ensures that Racket's macro expander will use the `#%app` in that lexical context.

This is discussed in [rackjure issue 25](https://github.com/greghendershott/rackjure/issues/25). However it is not really unique to rackjure. Racket allows `#%app` to be redefined. Threading macros are about an alternative syntax for application. They should use the notion of application in effect at the site of the macro invocation.

**Comment by lexi-lambda** [comment]
I admit I'm confused about why this is necessary. If `~>` expands into `(foo (bar (baz)))`, won't the `#%app` that gets introduced be the `#%app` at the use-site, not the `#%app` from the definition-site? Maybe I just don't understand quite how `#%app`-introduction works—I think I assumed it to be unhygienic, but perhaps I'm wrong?

**Comment by greghendershott** [comment]
It's been a long time since I worked on this so take what I say with a grain of salt. But:

A macro expands using the bindings in effect for the macro _definition_. Normally that's exactly what you want. For example:

```
#lang racket/base

(module macro-def racket/base
  (require (for-syntax racket/base syntax/parse))
  (define-syntax (add-nums stx)
    (syntax-parse stx
      [(_ x y) #'(+ x y)])) ;uses `+` from racket/base
  (provide add-nums))

(require 'macro-def)

;; Let's get cute and redefine `+`
(define (+ a b) ;shadow `+` from racket/base
  (string-append a b))

(displayln (+ "hi " "there")) ;uses `+` defined here, not racket/base
(displayln (add-nums 1 2))    ;uses `+` from `add-nums` definition

;; hi there
;; 3
```

More basically, the using module might not define `+` -- or whatever else the macro is using -- at all. The macro template needs the bindings from its definition.

But in this case we really do want `~>` to use the meaning of `#%app` from the macro use. That means taking the lexical context of the `~>` syntax given to our macro from the use. That lexical context's binding for `#%app` is what we want.

What confused me when implementing this, was, on what output syntax do I stick this lexical context? Sam pointed it out needs to go "on the parens" -- meaning on the `list` or `cons` of the syntax returned from the macro.  As discussed in [this comment thread](https://github.com/greghendershott/rackjure/commit/ba56d294145112b9db305d474b89dd9cb9f83660#commitcomment-5219535).

**Comment by lexi-lambda** [comment]
Thanks! I just learned a little bit more about how the macro expander works today. :smiley:

**Comment by greghendershott** [comment]
Thanks for doing this!  Unfortunately it looks like this is working only for the first application. I left a comment on commit 91652e1.

**Comment by lexi-lambda** [comment]
Hah, you're quite right. I feel silly for making that mistake! I'll push a fix.
