### ISSUE TITLE
some~> and some~>>

### ISSUE THREAD

**Issue by greghendershott** [lexi-lambda/threading#7]
rackjure provides `some~>` like Clojure's `some->`. Ditto for `>>` flavor. I'll need to continue to provide those.

AFAICT this is the same as your `and~>` and `and~>>`?
1. I'd welcome another set of eyeballs in case I'm missing a difference.
2. Assuming they're the same, I could re-provide `and~>{>}` with an alias `some~>{>}`, in rackjure. Unless you wanted to do so here. (Either is fine with me; I'm happy to do it in rackjure. Just wanted to ask first. Because if you _were_ to add it, later, it would break rackjure unless I required you `only-in`. But I'd prefer not to use `only-in`, I'd prefer that rackjure is just a simple reprovide of whatever you might add in the future.)

**Comment by lexi-lambda** [comment]
Yep, they are intended to be 100% the same, just with a different (hopefully slightly more obvious) name. If they function any differently in any way, it's probably a bug.
