### ISSUE TITLE
"1.0.0" is not a valid package version

### ISSUE THREAD

**Issue by greghendershott** [lexi-lambda/threading#8]
Could you please change the version number to, say, "1.1"?

As I'd mentioned in another issue, I need you to bump the version number, anyway, so that I can depend on user pulling something with commit efa04c or newer.

And also, "1.0.0" is not a `valid-version?` for the package manager. Although you can have a trailing 0 in the minor place, you can't in the build place:

```
#lang racket
(require version/utils)
(valid-version? "1.0")   ;#t
(valid-version? "1.0.0") ;#f
(valid-version? "1.0.1") ;#t
```

And indeed `"1.0.0"` is causing a problem:

https://travis-ci.org/greghendershott/rackjure/jobs/85218799#L146

```
$ raco pkg install --deps search-auto --link rackjure
Resolving "threading" via http://download.racket-lang.org/releases/6.2/catalog/
Resolving "threading" via http://pkgs.racket-lang.org
Downloading https://github.com/lexi-lambda/threading/tarball/efa04caf4f792381018b2cf07b1dc72f022ace7a
pkg: bad verson specification for threading: "1.0.0"
raco pkg install: version mismatch for dependency
  for package: rackjure
  mismatch packages:
   threading (have 0.0, need 1.0)

The command "raco pkg install --deps search-auto --link rackjure" exited with 1.

```

All Racket packages I've seen so far stick with `major.minor` versions. You don't have to, of course. But if you do use a release number you'll need to be careful that it's never 0.

**Comment by lexi-lambda** [comment]
Bah—you're right. That's a surprisingly odd issue. Have I mentioned I dislike the Racket package manager? :wink: Anyway, I should bump the version, problems with version strings or not.

**Comment by samth** [comment]
You could fix `valid-version?` to accept that.

**Comment by greghendershott** [comment]
@samth That would be good for the future. Although AFAICT that won't help the package manager code already baked into older Racket versions, which is my practical problem now.

@lexi-lambda Thanks for updating this! Unfortunately now I'm hitting some issues I just commented on at #5. Sorry.
