### ISSUE TITLE
Have a form of `->` that allows you to state what position to insert the result.

### ISSUE THREAD

**Issue by LeifAndersen** [lexi-lambda/threading#9]
At the moment, you seem to have `->` to insert the result as the first argument, and `->>` as the last.

What if I wanted a variant that would put it in the second argument, or even a variant that used the result to call the next function?

How hard would it be to have a variant that let users specify where they would like the result to go?

**Comment by lexi-lambda** [comment]
This already exists. See [“Changing the threading position”](http://lexi-lambda.github.io/threading/threading.html#%28part._.Changing_the_threading_position%29) in the docs, or look at the “hole marker” in the reference for `~>`. I’m going to close this, but feel free to continue the discussion if you think the docs need to be adjusted to make this more clear, or if you feel this doesn’t answer your question.

**Comment by LeifAndersen** [comment]
Oops, I didn't notice this. Thanks.
